### PR TITLE
Export video

### PR DESCRIPTION
**Pull request by charlielee**
This PR isn't ready for release yet. But I figured I might as well open it to give visibility to what is currently being worked on.

The biggest hold up has been having to write an entire nwjs packaging library due to nw-builder's shortcomings, and no currently available alternative.

New features:

- [x] Implement video export via ffmpeg #203
- [x] Upgrade to [nwjs-packager](https://github.com/charlielee/nwjs-packager) 1.x to support running `npm install --production` and fix numerous macOS issues #253
- [x] Test export feature on macOS
- [x] Fix export dialog being closeable during the export
- [x] Allow users to specify custom ffmpeg arguments 
- [x] Check if output file already exists to stop overwrite
- [x] Text export feature on Windows
- [x] Test export feature on Linux

### CODE REVIEW

**Comment by charlielee** [comment]
This is so close now! Just need to add a check that the video file isn't being overwritten

**Comment by charlielee** [comment]
I've noticed that videos exported with the default options seem to have difficulty opening in some media players (other than VLC, but what do you expect! 😂). I will need to poke around with the ffmpeg options

**Comment by AndreasDemenagas** [comment]
> I've noticed that videos exported with the default options seem to have difficulty opening in some media players (other than VLC, but what do you expect! 😂). I will need to poke around with the ffmpeg options

I have been able to reproduce this issue on macOS Catalina (10.15.6) using QuickTime Player.

**Comment by charlielee** [comment]
The QuickTime issue was due to the `crf` parameter being set to 0. I don't fully understand it but the docs describe "a subjective sane range is 17-28", so set to 17 I have!
https://trac.ffmpeg.org/wiki/Encode/H.264

If there are no more bugs, then this branch is now ready!

**Pull request merged**
