### PR TITLE
Move to Electron

### PR DESCRIPTION
**Pull request by charlielee**
This reworks the app to use Electron rather than NW.js #274. It will be a major PR once complete.

### CODE REVIEW

**Comment by le717** [comment]
How much more still needs to be done before this is complete? I don't think I have my USB webcam but I can test things out using my built-in laptop webcam.

**Comment by charlielee** [comment]
> How much more still needs to be done before this is complete?

@le717 I'd say it's about 90% complete now. The main things left are:

* Reimplement dialog box for selecting export video directory (selecting "Export video" will error at the moment)
* Some CSS fixes related to the general window layout (probably flexbox related)
* Restore keyboard shortcuts showing in the menu bar
* Test/configure electron-builder correctly
* Fix window dimensions not being stored when you choose the "Main Menu" menu bar option

I am hoping to finish very soon as I'm not working next week.

**Comment by AndreasDemenagas** [comment]
One thing I noticed while testing in macOS Big Sur is that the Menu Bar skips the first item "File" and puts in straight into the Menu Item of the application name. (See attached picture). 

This is probably because in macOS the first menu item is always reserved by the system and holds the name of the application. 

Checking if the platform is Darwin and if so skipping the first array item should fix this. 

Screenshot 2020-12-28 at 2 35 03 PM

**Comment by le717** [comment]
I'm going to recommend that once this is merged, tag it as 0.11.0, release it as a beta (also check the pre-release box in Releases), and ask people to download and use it. Don't add too many other changes. It's going to be easier having many others find issues related just to this and fix them for a next release than trying to find everything now.

**Comment by charlielee** [comment]
> One thing I noticed while testing in macOS Big Sur is that the Menu Bar skips the first item "File" and puts all the rows that should be in "File" straight into the Menu Item of the application name. (See attached picture).
> 
> This is probably because in macOS the first menu item is always reserved by the system and holds the name of the application.

@AndreasDemenagas Thanks for spotting this. I haven't tested on macOS/Linux yet so let me know if see anything else.

> I'm going to recommend that once this is merged, tag it as 0.11.0, release it as a beta (also check the pre-release box in Releases)

@le717  Yep, will bump to 0.11.0 after this is merged.

Also export video *should* work now. Note file paths with a space will fail to export as #278 is not merged into this branch yet.

**Comment by charlielee** [comment]
- [ ] Check possible bug with confirm take
- [ ] Finalise and test packages on Linux
- [ ] Finalise and test packages on macOS
- [ ] Finalise and test packages on Windows

**Comment by charlielee** [comment]
This is finally ready to go! 🚀 Hopefully I can actually work on some features again now.

**Pull request merged**
